obj-$(CONFIG_SND_SIMPLE_CARD_CORE) := simple-card-core.o

snd-soc-simple-card-objs	:= simple-card.o
snd-soc-simple-dpcm-card-objs	:= simple-dpcm-card.o

obj-$(CONFIG_SND_SIMPLE_CARD)	+= snd-soc-simple-card.o
obj-$(CONFIG_SND_SIMPLE_DPCM_CARD)	+= snd-soc-simple-dpcm-card.o
