# SPDX-License-Identifier: GPL-2.0
rcar-vcon-drm-y := rcar_vcon_drv.o \
		   rcar_vcon_vsp.o \
		   rcar_vcon_encoder.o \
		   rcar_vcon_crtc.o \
		   rcar_vcon_kms.o \
		   rcar_vcon_writeback.o

obj-$(CONFIG_DRM_RCAR_VCON)		+= rcar-vcon-drm.o

obj-$(CONFIG_DRM_RCAR_DW_DP) += rcar_dw_dp.o
