# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Renesas R-Car Taurus Ethernet
#
rcar-taurus-ether-y := rcar_taurus_ether.o \
		       rcar_taurus_ether_conn.o

obj-$(CONFIG_ETHER_RCAR_TAURUS)	+= rcar-taurus-ether.o
